deploy_testing:
  only:
    refs:
      - develop
  environment:
    name: testing
    url: $TESTING_DOMAIN
  script:
    - ssh $SSH_USERNAME@$TESTING_DOMAIN "cd codeshark/ && ./redeploy_frontend_testing.sh"
  only:
    - development
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - apt-get --yes --force-yes install rsync
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_testing:
  only:
    refs:
      - main
  environment:
    name: testing
    url: $DOMAIN
  script:
    - ssh $SSH_USERNAME@$DOMAIN "cd codeshark/ && ./redeploy_frontend_production.sh"
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - apt-get --yes --force-yes install rsync
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'